name: Build Kernel on GitHub workflows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with: 
        submodules: recursive

    - name: Install deps
      run: |
        sudo apt install -y git-core gnupg flex bc bison build-essential zip \
        curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev \
        x11proto-core-dev libx11-dev jq lib32z1-dev libgl1-mesa-dev libxml2-utils \
        xsltproc unzip fontconfig imagemagick python2 python3 python3-pip python3-dev \
        python-is-python3 schedtool ccache libtinfo5  libncurses5 lzop tmux libssl-dev \
        neofetch patchelf apktool dos2unix git-lfs default-jdk libxml-simple-perl ripgrep clang-11 &> /dev/null
    - name: Download tools
      run: bash dexk.sh --tools

    - name: Build DEXK (UNOFFICIAL) kernel
      run: bash dexk.sh --build

    - name: Upload kernel
      uses: actions/upload-artifact@v3
      with:
        name: deluxe-kernel
        path: v4.14*DEXK-POCO_X3*.zip
